# shared/db/pyproject.toml
[tool.poetry]
name = "db-core"
version = "0.1.0"
description = "Shared database configuration, models, and session management"
authors = ["Harshad K harshadk@datasmartpro.com"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = ">=0.111.0"
pydantic = ">=2.7.0"
python-dotenv = ">=1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"